
0
org.testng:testng
org.testng:testngtestng
Q
org.assertj:assertj-core5
org.assertj:assertj-coreAssertJ fluent assertions
P
com.puppycrawl.tools:checkstyle-
com.puppycrawl.tools:checkstyle
checkstyle
E
org.sonar:sonar-stash-plugin%
org.sonar:sonar-stash-pluginStash

mailgun
mailgunmailgun
*
	kunta-api
	kunta-apiKunta API Server
N
org.jboss.tools:openshift1
org.jboss.tools:openshiftjbosstools-openshift
O
game:game-execution-server1
game:game-execution-serverGameExecutionServer
6
numdifftools&
numdifftoolsPython :: Numdifftools
7
org.pipoware:pst-exp
org.pipoware:pst-exppst-exp
Ñ
/io.github.mbarre:schemacrawler-additional-lintsQ
/io.github.mbarre:schemacrawler-additional-lintsAdditional SchemaCrawler Lints
0
ru.urururu:sanity
ru.urururu:sanitysanity
L
game:game-platform-server/
game:game-platform-serverGamePlatformServer

thredds
threddsthredds
>
sonarqube-scanner)
sonarqube-scannerSonarScanner for NPM
¢
6com.kazuki43zoo.examples:mybatis-spring-boot-jpetstoreh
6com.kazuki43zoo.examples:mybatis-spring-boot-jpetstore.jpetstore on spring-boot + mybatis + thymeleaf
8
os-search-engine$
os-search-engineos-search-engine
•
Fcom.qualinsight.plugins.sonarqube:qualinsight-plugins-sonarqube-badges[
Fcom.qualinsight.plugins.sonarqube:qualinsight-plugins-sonarqube-badgesSVG Badges Plugin
^
'org.monarchinitiative.exomiser:exomiser3
'org.monarchinitiative.exomiser:exomiserexomiser
P
ZuInnoTe:hadoopcryptoledger1
ZuInnoTe:hadoopcryptoledgerHadoopCryptoLedger
>
ZuInnoTe:hadoopoffice%
ZuInnoTe:hadoopofficeHadoopOffice
]
#com.github.gcauchis:ScalablePress4j6
#com.github.gcauchis:ScalablePress4jScalablePress4j
b
$net.masterthought:cucumber-reporting:
$net.masterthought:cucumber-reportingcucumber-reporting
}
)org.sonarsource.samples:java-custom-rulesP
)org.sonarsource.samples:java-custom-rules#SonarQube Java Custom Rules Example
è
/org.sonarsource.samples:javascript-custom-rules\
/org.sonarsource.samples:javascript-custom-rules)SonarQube JavaScript Custom Rules Example
z
(org.sonarsource.samples:php-custom-rulesN
(org.sonarsource.samples:php-custom-rules"SonarQube PHP Custom Rules Example
z
(org.sonarsource.samples:rpg-custom-rulesN
(org.sonarsource.samples:rpg-custom-rules"SonarQube RPG Custom Rules Example
H
pl.damianszczepanik:silencio(
pl.damianszczepanik:silenciosilencio
V
 com.github.dannil:httpdownloader2
 com.github.dannil:httpdownloaderHttpDownloader

nlog
nlogNLog
Ä
*org.sonarsource.samples:cobol-custom-rulesR
*org.sonarsource.samples:cobol-custom-rules$SonarQube COBOL Custom Rules Example
4
liflab:beepbeep-3
liflab:beepbeep-3
BeepBeep 3
H
tlp-cassandra-reaper0
tlp-cassandra-reaperCassandra Reaper project
3
dismine:valentina
dismine:valentina	Valentina
ë
4de.tsystems.mms.apm:performance-signature-parent-pomY
4de.tsystems.mms.apm:performance-signature-parent-pom!Performance Signature: Parent Pom
8
pro.adamski:jvmVideo 
pro.adamski:jvmVideojvmVideo
K
com.abixen:abixen-platform-
com.abixen:abixen-platformAbixen Platform
'
maur1th:naxos
maur1th:naxosNaxos
D
lacliniqueducoureur-
lacliniqueducoureurLa Clinique du Coureur
/
QLNet-develop
QLNet-developQLNet-develop
.
hu.crs:codewars
hu.crs:codewarsCodewars
N
com.grindaga.developer-ipsum.
com.grindaga.developer-ipsumDeveloperIpsum
i
hbz.introx.direct:limetransJ
hbz.introx.direct:limetrans+limetrans - Library Metadata Transformation

posesor
posesorPosesor
w
+eu.michael-simons:wro4j-spring-boot-starterH
+eu.michael-simons:wro4j-spring-boot-starterWro4j Spring Boot Starter
,
io.trane:future
io.trane:futurefuture

Cubes
CubesCubes
?
org.jboss.tools:base'
org.jboss.tools:basejbosstools-base
M
org.jboss.tools:server.all/
org.jboss.tools:server.alljbosstools-server
Y
org.jmxtrans:jmxtrans-parent9
org.jmxtrans:jmxtrans-parentJmxTrans - parent project
O
vil:backend-spring9
vil:backend-spring#Voornamen in liedjes spring backend
g
com.github.oshi:oshi-parentH
com.github.oshi:oshi-parent)Operating System and Hardware Information
r
*my.zin.rashidi.demo:spring-boot-data-auditD
*my.zin.rashidi.demo:spring-boot-data-auditspring-boot-data-audit
?
pl.olafgoj:hackingnews%
pl.olafgoj:hackingnewshackingnews
F
mvs-services:mvs-services)
mvs-services:mvs-servicesmvs-services
C
uk.ac.diamond.ispyb.api(
uk.ac.diamond.ispyb.apiGDA ISPyB API
.
	fusetools!
	fusetoolsRed Hat Fuse Tooling
<
org.ovirt.engine:root#
org.ovirt.engine:root
ovirt-root
W
io.fabric8:docker-maven-plugin5
io.fabric8:docker-maven-plugindocker-maven-plugin
h
%io.fabric8:fabric8-maven-plugin-build?
%io.fabric8:fabric8-maven-plugin-buildFabric8 Maven :: Build
°
5io.github.jhipster.sample:jhipster-sample-applicationh
5io.github.jhipster.sample:jhipster-sample-application/jhipsterSampleApplication generated by jhipster
0
com.restfb:restfb
com.restfb:restfbRestFB
N
org.mazarineblue:MazarineBlue-
org.mazarineblue:MazarineBlueMazarineBlue
5
org.mybatis:mybatis
org.mybatis:mybatismybatis
J
org.mybatis:mybatis-spring,
org.mybatis:mybatis-springmybatis-spring
ã
-com.hello2morrow:sonar-sonargraph-integrationZ
-com.hello2morrow:sonar-sonargraph-integration)SonarQube Sonargraph 9 Integration Plugin
&

ministocks

ministocks
Ministocks
#
	andstatus
	andstatus	AndStatus
D
org.jacoco:org.jacoco.build%
org.jacoco:org.jacoco.buildJaCoCo
E
org.eclipse.eclemma:eclemma&
org.eclipse.eclemma:eclemmaeclemma
§
Ecom.qualinsight.plugins.sonarqube:qualinsight-plugins-sonarqube-smell[
Ecom.qualinsight.plugins.sonarqube:qualinsight-plugins-sonarqube-smellCode Smells Plugin